#!/bin/bash

# Modify the cp (classpath) variable to match the paths on your system...
cp=/Users/guy/Library/Java/lib/jcalc-1.0.0.jar:/Users/guy/Library/Java/lib/jline-3.19.1-SNAPSHOT.jar:/Users/guy/Library/Java/lib/Logger-1.0.jar

mainclass=com.guy.calc.Main

java -classpath $cp $mainclass
